server:
  port: 8080

spring:
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/TEST
    username: TEST
    password: TEST

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 1252c8caf52e206b0ca710bc49a7eb56
            client-secret: YJZQbNNmhvURdI71Ir5uoHeoQphGXWxf
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image,account_email
            client-authentication-method: client_secret_post
          naver:
            client-name: naver
            client-id: E9DXSM178br86t3tNd0N
            client-secret: LOhnvthT57
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
            client-authentication-method: client_secret_post
          google:
            client-name: google
            client-id: 642859891963-suerd1ivck2b3tpc45qsol92qgrmtb8o.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  data:
    redis:
      host: localhost
      port: 6379